[2024-11-02T13:35:49.327+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-02T13:35:49.357+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tem.bash_task3 manual__2024-11-02T13:35:31.491417+00:00 [queued]>
[2024-11-02T13:35:49.371+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tem.bash_task3 manual__2024-11-02T13:35:31.491417+00:00 [queued]>
[2024-11-02T13:35:49.372+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 4
[2024-11-02T13:35:49.400+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): bash_task3> on 2024-11-02 13:35:31.491417+00:00
[2024-11-02T13:35:49.408+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=572) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-02T13:35:49.409+0000] {standard_task_runner.py:72} INFO - Started process 573 to run task
[2024-11-02T13:35:49.411+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tem', 'bash_task3', 'manual__2024-11-02T13:35:31.491417+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/templatin/template.py', '--cfg-path', '/tmp/tmpmgqd2ap3']
[2024-11-02T13:35:49.413+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask bash_task3
[2024-11-02T13:35:49.485+0000] {task_command.py:467} INFO - Running <TaskInstance: tem.bash_task3 manual__2024-11-02T13:35:31.491417+00:00 [running]> on host fe3e688f2b29
[2024-11-02T13:35:49.615+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ade' AIRFLOW_CTX_DAG_ID='tem' AIRFLOW_CTX_TASK_ID='bash_task3' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T13:35:31.491417+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-02T13:35:31.491417+00:00'
[2024-11-02T13:35:49.616+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-02T13:35:49.638+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-02T13:35:49.639+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "2"']
[2024-11-02T13:35:49.651+0000] {subprocess.py:86} INFO - Output:
[2024-11-02T13:35:49.653+0000] {subprocess.py:93} INFO - 2
[2024-11-02T13:35:49.654+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-02T13:35:49.697+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-02T13:35:49.698+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=tem, task_id=bash_task3, run_id=manual__2024-11-02T13:35:31.491417+00:00, execution_date=20241102T133531, start_date=20241102T133549, end_date=20241102T133549
[2024-11-02T13:35:49.749+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-02T13:35:49.774+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-02T13:35:49.784+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
