[2024-10-17T22:11:32.125+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T22:11:32.209+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_postgres manual__2024-10-17T22:11:25.552135+00:00 [queued]>
[2024-10-17T22:11:32.261+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_postgres manual__2024-10-17T22:11:25.552135+00:00 [queued]>
[2024-10-17T22:11:32.262+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-17T22:11:32.383+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2024-10-17 22:11:25.552135+00:00
[2024-10-17T22:11:32.422+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2073) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-17T22:11:32.447+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_s3', 'load_to_postgres', 'manual__2024-10-17T22:11:25.552135+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/prod.py', '--cfg-path', '/tmp/tmpylva1_x3']
[2024-10-17T22:11:32.459+0000] {standard_task_runner.py:72} INFO - Started process 2081 to run task
[2024-10-17T22:11:32.470+0000] {standard_task_runner.py:105} INFO - Job 74: Subtask load_to_postgres
[2024-10-17T22:11:32.743+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_to_s3.load_to_postgres manual__2024-10-17T22:11:25.552135+00:00 [running]> on host 1b4cad12ae67
[2024-10-17T22:11:33.059+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='postgres_to_s3' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T22:11:25.552135+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-17T22:11:25.552135+00:00'
[2024-10-17T22:11:33.061+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T22:11:33.115+0000] {base.py:84} INFO - Retrieving connection 'post_s3'
[2024-10-17T22:11:33.123+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-17T22:11:33.146+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T22:11:33.147+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=postgres_to_s3, task_id=load_to_postgres, run_id=manual__2024-10-17T22:11:25.552135+00:00, execution_date=20241017T221125, start_date=20241017T221132, end_date=20241017T221133
[2024-10-17T22:11:33.227+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-17T22:11:33.243+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
