[2024-10-19T17:14:26.258+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-19T17:14:26.280+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_s3 manual__2024-10-19T16:59:43.927739+00:00 [queued]>
[2024-10-19T17:14:26.295+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_s3 manual__2024-10-19T16:59:43.927739+00:00 [queued]>
[2024-10-19T17:14:26.296+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 3
[2024-10-19T17:14:26.322+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_to_s3> on 2024-10-19 16:59:43.927739+00:00
[2024-10-19T17:14:26.331+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1810) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-19T17:14:26.335+0000] {standard_task_runner.py:72} INFO - Started process 1812 to run task
[2024-10-19T17:14:26.334+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_s3', 'load_to_s3', 'manual__2024-10-19T16:59:43.927739+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/prod.py', '--cfg-path', '/tmp/tmprfjfy648']
[2024-10-19T17:14:26.338+0000] {standard_task_runner.py:105} INFO - Job 47: Subtask load_to_s3
[2024-10-19T17:14:26.411+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_to_s3.load_to_s3 manual__2024-10-19T16:59:43.927739+00:00 [running]> on host 533638d20908
[2024-10-19T17:14:26.570+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='postgres_to_s3' AIRFLOW_CTX_TASK_ID='load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-10-19T16:59:43.927739+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-19T16:59:43.927739+00:00'
[2024-10-19T17:14:26.572+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-19T17:14:26.636+0000] {base.py:84} INFO - Retrieving connection 'post_s3'
[2024-10-19T17:14:26.652+0000] {base.py:84} INFO - Retrieving connection 'post_s3'
[2024-10-19T17:14:26.943+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-19T17:14:26.957+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-19T17:14:26.958+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=postgres_to_s3, task_id=load_to_s3, run_id=manual__2024-10-19T16:59:43.927739+00:00, execution_date=20241019T165943, start_date=20241019T171426, end_date=20241019T171426
[2024-10-19T17:14:27.034+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-19T17:14:27.072+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-19T17:14:27.085+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
