[2024-11-25T01:59:05.080+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-25T01:59:05.135+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ckckc.object_datalake manual__2024-11-25T01:58:47.632514+00:00 [queued]>
[2024-11-25T01:59:05.157+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ckckc.object_datalake manual__2024-11-25T01:58:47.632514+00:00 [queued]>
[2024-11-25T01:59:05.159+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2024-11-25T01:59:05.212+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): object_datalake> on 2024-11-25 01:58:47.632514+00:00
[2024-11-25T01:59:05.229+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=376) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-25T01:59:05.236+0000] {standard_task_runner.py:72} INFO - Started process 378 to run task
[2024-11-25T01:59:05.240+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ckckc', 'object_datalake', 'manual__2024-11-25T01:58:47.632514+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/capstone_***/refractor_code_dag.py', '--cfg-path', '/tmp/tmpnxcditm9']
[2024-11-25T01:59:05.247+0000] {standard_task_runner.py:105} INFO - Job 125: Subtask object_datalake
[2024-11-25T01:59:05.382+0000] {task_command.py:467} INFO - Running <TaskInstance: ckckc.object_datalake manual__2024-11-25T01:58:47.632514+00:00 [running]> on host 18d777ba90d1
[2024-11-25T01:59:05.649+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='adewunmi' AIRFLOW_CTX_DAG_ID='ckckc' AIRFLOW_CTX_TASK_ID='object_datalake' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T01:58:47.632514+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-25T01:58:47.632514+00:00'
[2024-11-25T01:59:05.652+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-25T01:59:05.700+0000] {extract_load_to_s3.py:20} INFO - GET request initiating
[2024-11-25T01:59:07.800+0000] {extract_load_to_s3.py:25} INFO - API request connection is okay
[2024-11-25T01:59:08.152+0000] {extract_load_to_s3.py:31} INFO - Response data received successfully
[2024-11-25T01:59:16.615+0000] {extract_load_to_s3.py:86} INFO - Data successfully written to S3 in Parquet format.
[2024-11-25T01:59:16.637+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-25T01:59:16.694+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-25T01:59:16.696+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ckckc, task_id=object_datalake, run_id=manual__2024-11-25T01:58:47.632514+00:00, execution_date=20241125T015847, start_date=20241125T015905, end_date=20241125T015916
[2024-11-25T01:59:16.837+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-25T01:59:16.856+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
