[2024-10-07T16:08:13.091+0000] {processor.py:186} INFO - Started process (PID=18258) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:08:13.094+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:08:13.097+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:08:13.096+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:08:13.137+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:08:13.126+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:08:13.140+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:08:13.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.121 seconds
[2024-10-07T16:08:43.346+0000] {processor.py:186} INFO - Started process (PID=18323) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:08:43.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:08:43.350+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:08:43.349+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:08:43.369+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:08:43.364+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:08:43.371+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:08:43.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.072 seconds
[2024-10-07T16:09:13.509+0000] {processor.py:186} INFO - Started process (PID=18388) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:09:13.510+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:09:13.512+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:09:13.512+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:09:13.531+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:09:13.526+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:09:13.533+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:09:13.563+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.065 seconds
[2024-10-07T16:09:43.698+0000] {processor.py:186} INFO - Started process (PID=18453) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:09:43.700+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:09:43.702+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:09:43.701+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:09:43.719+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:09:43.714+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:09:43.720+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:09:43.758+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.068 seconds
[2024-10-07T16:10:14.775+0000] {processor.py:186} INFO - Started process (PID=18518) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:10:14.777+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:10:14.778+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:10:14.778+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:10:14.806+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:10:14.798+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:10:14.808+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:10:14.847+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.080 seconds
[2024-10-07T16:10:45.320+0000] {processor.py:186} INFO - Started process (PID=18583) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:10:45.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:10:45.323+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:10:45.322+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:10:45.341+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:10:45.336+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:10:45.342+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:10:45.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.069 seconds
[2024-10-07T16:11:15.680+0000] {processor.py:186} INFO - Started process (PID=18648) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:11:15.681+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:11:15.684+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:11:15.683+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:11:15.702+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:11:15.698+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:11:15.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:11:15.734+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.064 seconds
[2024-10-07T16:11:46.111+0000] {processor.py:186} INFO - Started process (PID=18713) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:11:46.112+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:11:46.114+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:11:46.113+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:11:46.132+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:11:46.127+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:11:46.134+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:11:46.165+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.063 seconds
[2024-10-07T16:12:16.256+0000] {processor.py:186} INFO - Started process (PID=18778) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:12:16.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:12:16.261+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:12:16.260+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:12:16.282+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:12:16.276+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:12:16.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:12:16.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.074 seconds
[2024-10-07T16:12:47.140+0000] {processor.py:186} INFO - Started process (PID=18843) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:12:47.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:12:47.145+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:12:47.145+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:12:47.292+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:12:47.235+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:12:47.321+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:12:47.397+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.289 seconds
[2024-10-07T16:13:17.582+0000] {processor.py:186} INFO - Started process (PID=18907) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:13:17.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:13:17.587+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:13:17.586+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:13:17.616+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:13:17.610+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:13:17.619+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:13:17.653+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.084 seconds
[2024-10-07T16:13:48.536+0000] {processor.py:186} INFO - Started process (PID=18972) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:13:48.540+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:13:48.544+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:13:48.543+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:13:48.591+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:13:48.580+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:13:48.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:13:48.663+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.146 seconds
[2024-10-07T16:14:18.969+0000] {processor.py:186} INFO - Started process (PID=19037) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:14:18.971+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:14:18.973+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:14:18.972+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:14:18.993+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:14:18.988+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:14:18.995+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:14:19.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.178 seconds
[2024-10-07T16:14:49.252+0000] {processor.py:186} INFO - Started process (PID=19102) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:14:49.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:14:49.255+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:14:49.255+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:14:49.273+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:14:49.269+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:14:49.274+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:14:49.308+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.065 seconds
[2024-10-07T16:15:19.400+0000] {processor.py:186} INFO - Started process (PID=19167) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:15:19.401+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:15:19.403+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:15:19.403+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:15:19.420+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:15:19.416+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:15:19.422+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:15:19.465+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.074 seconds
[2024-10-07T16:15:50.156+0000] {processor.py:186} INFO - Started process (PID=19230) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:15:50.158+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:15:50.161+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:15:50.160+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:15:50.192+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:15:50.187+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:15:50.195+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:15:50.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.117 seconds
[2024-10-07T16:16:20.849+0000] {processor.py:186} INFO - Started process (PID=19301) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:16:20.851+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:16:20.853+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:16:20.852+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:16:20.871+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:16:20.867+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:16:20.873+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:16:20.916+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.081 seconds
[2024-10-07T16:16:51.453+0000] {processor.py:186} INFO - Started process (PID=19366) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:16:51.455+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:16:51.458+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:16:51.457+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:16:51.502+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:16:51.481+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:16:51.510+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:16:51.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.131 seconds
[2024-10-07T16:17:21.934+0000] {processor.py:186} INFO - Started process (PID=19431) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:17:21.936+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:17:21.938+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:17:21.938+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:17:21.962+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:17:21.957+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:17:21.964+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:17:22.006+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.086 seconds
[2024-10-07T16:17:52.551+0000] {processor.py:186} INFO - Started process (PID=19496) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:17:52.553+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:17:52.556+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:17:52.555+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:17:52.574+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:17:52.570+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:17:52.576+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:17:52.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.080 seconds
[2024-10-07T16:18:22.981+0000] {processor.py:186} INFO - Started process (PID=19561) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:18:22.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:18:22.986+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:18:22.985+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:18:23.012+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:18:23.001+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:18:23.015+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:18:23.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.121 seconds
[2024-10-07T16:18:53.391+0000] {processor.py:186} INFO - Started process (PID=19626) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:18:53.393+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:18:53.395+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:18:53.394+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:18:53.416+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:18:53.411+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:18:53.419+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:18:53.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.070 seconds
[2024-10-07T16:19:24.025+0000] {processor.py:186} INFO - Started process (PID=19690) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:19:24.027+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:19:24.030+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:19:24.029+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:19:24.051+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:19:24.045+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:19:24.054+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:19:24.089+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.077 seconds
[2024-10-07T16:19:55.144+0000] {processor.py:186} INFO - Started process (PID=19756) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:19:55.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:19:55.149+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:19:55.148+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:19:55.184+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:19:55.177+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:19:55.187+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:19:55.249+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.123 seconds
[2024-10-07T16:20:26.073+0000] {processor.py:186} INFO - Started process (PID=19821) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:20:26.075+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:20:26.079+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:20:26.078+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:20:26.123+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:20:26.118+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:20:26.125+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:20:26.168+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.115 seconds
[2024-10-07T16:20:56.683+0000] {processor.py:186} INFO - Started process (PID=19886) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:20:56.685+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:20:56.688+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:20:56.687+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:20:56.718+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:20:56.712+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:20:56.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:20:56.766+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.096 seconds
[2024-10-07T16:21:27.349+0000] {processor.py:186} INFO - Started process (PID=19951) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:21:27.351+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:21:27.353+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:21:27.353+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:21:27.383+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:21:27.376+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:21:27.385+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:21:27.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.107 seconds
[2024-10-07T16:21:58.083+0000] {processor.py:186} INFO - Started process (PID=20016) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:21:58.085+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:21:58.087+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:21:58.086+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:21:58.115+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:21:58.110+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:21:58.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:21:58.158+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.091 seconds
[2024-10-07T16:22:28.459+0000] {processor.py:186} INFO - Started process (PID=20081) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:22:28.461+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:22:28.464+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:22:28.463+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:22:28.497+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:22:28.490+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:22:28.499+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:22:28.544+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.106 seconds
[2024-10-07T16:22:59.221+0000] {processor.py:186} INFO - Started process (PID=20146) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:22:59.222+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:22:59.225+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:22:59.224+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:22:59.244+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:22:59.240+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:22:59.246+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:22:59.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.078 seconds
[2024-10-07T16:23:29.620+0000] {processor.py:186} INFO - Started process (PID=20211) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:23:29.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:23:29.634+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:23:29.624+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:23:29.699+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:23:29.683+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:23:29.702+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:23:29.788+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.203 seconds
[2024-10-07T16:24:00.081+0000] {processor.py:186} INFO - Started process (PID=20276) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:24:00.083+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:24:00.086+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:24:00.085+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:24:00.113+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:24:00.109+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:24:00.115+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:24:00.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.082 seconds
[2024-10-07T16:24:30.510+0000] {processor.py:186} INFO - Started process (PID=20339) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:24:30.513+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:24:30.515+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:24:30.514+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:24:30.538+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:24:30.533+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:24:30.540+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:24:30.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.080 seconds
[2024-10-07T16:25:01.130+0000] {processor.py:186} INFO - Started process (PID=20404) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:25:01.131+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:25:01.134+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:25:01.133+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:25:01.153+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:25:01.148+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:25:01.155+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:25:01.182+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.062 seconds
[2024-10-07T16:25:31.797+0000] {processor.py:186} INFO - Started process (PID=20469) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:25:31.798+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:25:31.801+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:25:31.800+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:25:31.824+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:25:31.818+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:25:31.827+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:25:31.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.081 seconds
[2024-10-07T16:26:02.104+0000] {processor.py:186} INFO - Started process (PID=20535) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:26:02.114+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:26:02.118+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:26:02.117+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:26:02.184+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:26:02.168+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:26:02.187+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:26:02.245+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.157 seconds
[2024-10-07T16:26:32.474+0000] {processor.py:186} INFO - Started process (PID=20600) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:26:32.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:26:32.478+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:26:32.477+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:26:32.498+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:26:32.493+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:26:32.500+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:26:32.531+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.068 seconds
[2024-10-07T16:27:03.140+0000] {processor.py:186} INFO - Started process (PID=20661) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:27:03.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:27:03.144+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:27:03.143+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:27:03.164+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:27:03.159+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:27:03.166+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:27:03.199+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.073 seconds
[2024-10-07T16:27:33.794+0000] {processor.py:186} INFO - Started process (PID=20726) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:27:33.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:27:33.800+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:27:33.799+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:27:33.827+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:27:33.821+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:27:33.830+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:27:33.883+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.101 seconds
[2024-10-07T16:28:04.514+0000] {processor.py:186} INFO - Started process (PID=20792) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:28:04.516+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:28:04.519+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:28:04.518+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:28:04.555+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:28:04.546+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:28:04.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:28:04.608+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.109 seconds
[2024-10-07T16:28:34.815+0000] {processor.py:186} INFO - Started process (PID=20858) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:28:34.817+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:28:34.819+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:28:34.818+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:28:34.837+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:28:34.833+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:28:34.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:28:34.874+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.074 seconds
[2024-10-07T16:29:06.142+0000] {processor.py:186} INFO - Started process (PID=20924) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:29:06.144+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:29:06.147+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:29:06.147+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:29:06.178+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:29:06.171+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:29:06.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:29:06.218+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.096 seconds
[2024-10-07T16:29:36.786+0000] {processor.py:186} INFO - Started process (PID=20988) to work on /opt/airflow/dags/okay.py
[2024-10-07T16:29:36.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/okay.py for tasks to queue
[2024-10-07T16:29:36.791+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:29:36.790+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/okay.py
[2024-10-07T16:29:36.812+0000] {logging_mixin.py:190} INFO - [2024-10-07T16:29:36.807+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/okay.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/okay.py", line 3, in <module>
    from airflow.providers.amazon.aws.transfers.s3_to_snowflake import S3ToSnowflakeOperator
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.transfers.s3_to_snowflake'
[2024-10-07T16:29:36.814+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/okay.py
[2024-10-07T16:29:36.847+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/okay.py took 0.073 seconds
