[2024-11-13T23:11:32.894+0000] {processor.py:186} INFO - Started process (PID=2921) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:11:32.895+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:11:32.898+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:11:32.898+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:11:32.919+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:11:32.914+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 20
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 14
[2024-11-13T23:11:32.921+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:11:32.950+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.063 seconds
[2024-11-13T23:12:03.778+0000] {processor.py:186} INFO - Started process (PID=2930) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:12:03.780+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:12:03.783+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:12:03.783+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:12:03.802+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:12:03.800+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 20
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 14
[2024-11-13T23:12:03.803+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:12:03.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.059 seconds
[2024-11-13T23:12:34.520+0000] {processor.py:186} INFO - Started process (PID=2939) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:12:34.521+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:12:34.524+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:12:34.524+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:12:34.545+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:12:34.544+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 20
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 14
[2024-11-13T23:12:34.546+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:12:34.582+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.069 seconds
[2024-11-13T23:13:05.171+0000] {processor.py:186} INFO - Started process (PID=2948) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:13:05.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:13:05.178+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:13:05.178+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:13:05.226+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:13:05.224+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 20
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 14
[2024-11-13T23:13:05.228+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:13:05.290+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.131 seconds
[2024-11-13T23:13:11.242+0000] {processor.py:186} INFO - Started process (PID=2949) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:13:11.243+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:13:11.251+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:13:11.251+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:13:11.274+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:13:11.273+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 21
    
    ^
IndentationError: expected an indented block after 'with' statement on line 14
[2024-11-13T23:13:11.275+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:13:11.315+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.083 seconds
[2024-11-13T23:13:12.311+0000] {processor.py:186} INFO - Started process (PID=2950) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:13:12.312+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:13:12.315+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:13:12.315+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:13:12.336+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:13:12.335+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 22
    
    ^
IndentationError: expected an indented block after 'with' statement on line 14
[2024-11-13T23:13:12.337+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:13:12.360+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.058 seconds
[2024-11-13T23:13:15.369+0000] {processor.py:186} INFO - Started process (PID=2951) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:13:15.370+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:13:15.373+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:13:15.373+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:13:15.415+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:13:15.408+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 22, in <module>
    ta
NameError: name 'ta' is not defined
[2024-11-13T23:13:15.418+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:13:15.444+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.083 seconds
[2024-11-13T23:13:46.349+0000] {processor.py:186} INFO - Started process (PID=2961) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:13:46.350+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:13:46.353+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:13:46.353+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:13:46.384+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:13:46.376+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 22, in <module>
    ta
NameError: name 'ta' is not defined
[2024-11-13T23:13:46.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:13:46.411+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.070 seconds
[2024-11-13T23:14:16.973+0000] {processor.py:186} INFO - Started process (PID=2970) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:14:16.974+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:14:16.976+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:14:16.976+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:14:17.005+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:14:16.998+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 22, in <module>
    ta
NameError: name 'ta' is not defined
[2024-11-13T23:14:17.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:14:17.040+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.077 seconds
[2024-11-13T23:14:47.737+0000] {processor.py:186} INFO - Started process (PID=2979) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:14:47.739+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:14:47.745+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:14:47.744+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:14:47.776+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:14:47.769+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 22, in <module>
    ta
NameError: name 'ta' is not defined
[2024-11-13T23:14:47.779+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:14:47.804+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.078 seconds
[2024-11-13T23:15:18.467+0000] {processor.py:186} INFO - Started process (PID=2988) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:15:18.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:15:18.471+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:15:18.470+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:15:18.498+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:15:18.491+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 22, in <module>
    ta
NameError: name 'ta' is not defined
[2024-11-13T23:15:18.500+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:15:18.531+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.075 seconds
[2024-11-13T23:15:49.424+0000] {processor.py:186} INFO - Started process (PID=3004) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:15:49.427+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:15:49.433+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:15:49.430+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:15:49.503+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:15:49.493+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 22, in <module>
    ta
NameError: name 'ta' is not defined
[2024-11-13T23:15:49.509+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:15:49.560+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.147 seconds
[2024-11-13T23:16:20.045+0000] {processor.py:186} INFO - Started process (PID=3013) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:16:20.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:16:20.051+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:16:20.050+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:16:20.079+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:16:20.072+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 22, in <module>
    ta
NameError: name 'ta' is not defined
[2024-11-13T23:16:20.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:16:20.115+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.078 seconds
[2024-11-13T23:16:50.969+0000] {processor.py:186} INFO - Started process (PID=3022) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:16:50.970+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:16:50.975+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:16:50.975+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:16:51.017+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:16:51.008+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 22, in <module>
    ta
NameError: name 'ta' is not defined
[2024-11-13T23:16:51.020+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:16:51.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.098 seconds
[2024-11-13T23:17:21.844+0000] {processor.py:186} INFO - Started process (PID=3031) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:17:21.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:17:21.849+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:17:21.849+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:17:21.879+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:17:21.872+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 22, in <module>
    ta
NameError: name 'ta' is not defined
[2024-11-13T23:17:21.883+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:17:21.909+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.073 seconds
[2024-11-13T23:17:51.968+0000] {processor.py:186} INFO - Started process (PID=3041) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:17:51.969+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:17:51.973+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:17:51.973+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:17:52.007+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:17:52.001+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 22, in <module>
    ta
NameError: name 'ta' is not defined
[2024-11-13T23:17:52.011+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:17:52.042+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.085 seconds
[2024-11-13T23:18:22.494+0000] {processor.py:186} INFO - Started process (PID=3050) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:18:22.496+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:18:22.499+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:18:22.498+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:18:22.533+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:18:22.526+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 22, in <module>
    ta
NameError: name 'ta' is not defined
[2024-11-13T23:18:22.536+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:18:22.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.090 seconds
[2024-11-13T23:18:53.292+0000] {processor.py:186} INFO - Started process (PID=3059) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:18:53.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:18:53.298+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:18:53.298+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:18:53.341+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:18:53.323+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 22, in <module>
    ta
NameError: name 'ta' is not defined
[2024-11-13T23:18:53.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:18:53.386+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.104 seconds
[2024-11-13T23:19:24.047+0000] {processor.py:186} INFO - Started process (PID=3068) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:19:24.048+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:19:24.053+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:19:24.052+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:19:24.079+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:19:24.073+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 22, in <module>
    ta
NameError: name 'ta' is not defined
[2024-11-13T23:19:24.081+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:19:24.108+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.070 seconds
[2024-11-13T23:19:47.754+0000] {processor.py:186} INFO - Started process (PID=3071) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:19:47.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:19:47.759+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:19:47.758+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:19:47.806+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:19:47.798+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 3, in <module>
    from airflow.operators.p_operator import BashOperator
ModuleNotFoundError: No module named 'airflow.operators.p_operator'
[2024-11-13T23:19:47.809+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:19:47.869+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.130 seconds
[2024-11-13T23:19:48.984+0000] {processor.py:186} INFO - Started process (PID=3072) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:19:48.985+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:19:48.989+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:19:48.988+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:19:49.028+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:19:49.020+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 3, in <module>
    from airflow.operators.pyt_operator import BashOperator
ModuleNotFoundError: No module named 'airflow.operators.pyt_operator'
[2024-11-13T23:19:49.030+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:19:49.068+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.094 seconds
[2024-11-13T23:19:59.239+0000] {processor.py:186} INFO - Started process (PID=3079) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:19:59.240+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:19:59.243+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:19:59.243+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:19:59.320+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:19:59.311+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 3, in <module>
    from airflow.operators.pyth_operator import BashOperator
ModuleNotFoundError: No module named 'airflow.operators.pyth_operator'
[2024-11-13T23:19:59.323+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:19:59.359+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.127 seconds
[2024-11-13T23:20:01.358+0000] {processor.py:186} INFO - Started process (PID=3080) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:01.359+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:01.363+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:01.362+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:01.416+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:01.404+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 3, in <module>
    from airflow.operators.python_operator import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators.python_operator' (unknown location)
[2024-11-13T23:20:01.421+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:01.476+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.128 seconds
[2024-11-13T23:20:06.551+0000] {processor.py:186} INFO - Started process (PID=3081) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:06.552+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:06.558+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:06.557+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:06.605+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:06.592+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 3, in <module>
    from airflow.operators.python_operator import Operator
ImportError: cannot import name 'Operator' from 'airflow.operators.python_operator' (unknown location). Did you mean: 'operators'?
[2024-11-13T23:20:06.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:06.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.123 seconds
[2024-11-13T23:20:07.704+0000] {processor.py:186} INFO - Started process (PID=3082) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:07.706+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:07.712+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:07.712+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:07.759+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:07.749+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 3, in <module>
    from airflow.operators.python_operator import POperator
ImportError: cannot import name 'POperator' from 'airflow.operators.python_operator' (unknown location). Did you mean: 'operators'?
[2024-11-13T23:20:07.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:07.798+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.104 seconds
[2024-11-13T23:20:11.845+0000] {processor.py:186} INFO - Started process (PID=3083) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:11.846+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:11.849+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:11.849+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:11.888+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:11.880+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 3, in <module>
    from airflow.operators.python_operator import PyOperator
ImportError: cannot import name 'PyOperator' from 'airflow.operators.python_operator' (unknown location). Did you mean: 'operators'?
[2024-11-13T23:20:11.894+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:11.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.082 seconds
[2024-11-13T23:20:14.043+0000] {processor.py:186} INFO - Started process (PID=3086) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:14.044+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:14.047+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:14.047+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:14.108+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:14.097+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 3, in <module>
    from airflow.operators.python_operator import PytOperator
ImportError: cannot import name 'PytOperator' from 'airflow.operators.python_operator' (unknown location)
[2024-11-13T23:20:14.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:14.148+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.112 seconds
[2024-11-13T23:20:15.227+0000] {processor.py:186} INFO - Started process (PID=3087) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:15.231+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:15.234+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:15.234+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:15.284+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:15.276+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 22, in <module>
    ta
NameError: name 'ta' is not defined
[2024-11-13T23:20:15.286+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:15.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.093 seconds
[2024-11-13T23:20:21.394+0000] {processor.py:186} INFO - Started process (PID=3094) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:21.398+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:21.418+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:21.417+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:21.581+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:21.565+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 24, in <module>
    ta
NameError: name 'ta' is not defined
[2024-11-13T23:20:21.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:21.648+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.266 seconds
[2024-11-13T23:20:22.737+0000] {processor.py:186} INFO - Started process (PID=3095) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:22.739+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:22.742+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:22.741+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:22.764+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:22.763+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6
    from 
         ^
SyntaxError: invalid syntax
[2024-11-13T23:20:22.765+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:22.793+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.065 seconds
[2024-11-13T23:20:28.915+0000] {processor.py:186} INFO - Started process (PID=3096) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:28.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:28.920+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:28.920+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:28.942+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:28.941+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6
    from fun
            ^
SyntaxError: invalid syntax
[2024-11-13T23:20:28.943+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:28.984+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.079 seconds
[2024-11-13T23:20:32.163+0000] {processor.py:186} INFO - Started process (PID=3097) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:32.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:32.168+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:32.168+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:32.190+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:32.188+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6
    from function in
                  ^^
SyntaxError: invalid syntax
[2024-11-13T23:20:32.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:32.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.061 seconds
[2024-11-13T23:20:33.216+0000] {processor.py:186} INFO - Started process (PID=3098) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:33.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:33.222+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:33.222+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:33.248+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:33.246+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6
    from function i
                  ^
SyntaxError: invalid syntax
[2024-11-13T23:20:33.250+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:33.276+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.067 seconds
[2024-11-13T23:20:34.449+0000] {processor.py:186} INFO - Started process (PID=3099) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:34.451+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:34.456+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:34.455+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:34.489+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:34.487+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6
    from function 
                  ^
SyntaxError: invalid syntax
[2024-11-13T23:20:34.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:34.524+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.087 seconds
[2024-11-13T23:20:36.606+0000] {processor.py:186} INFO - Started process (PID=3100) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:36.607+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:36.611+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:36.610+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:36.635+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:36.633+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6
    from function impo
                  ^^^^
SyntaxError: invalid syntax
[2024-11-13T23:20:36.636+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:36.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.082 seconds
[2024-11-13T23:20:37.657+0000] {processor.py:186} INFO - Started process (PID=3101) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:37.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:37.662+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:37.662+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:37.716+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:37.714+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6
    from function import
                        ^
SyntaxError: invalid syntax
[2024-11-13T23:20:37.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:37.783+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.134 seconds
[2024-11-13T23:20:38.792+0000] {processor.py:186} INFO - Started process (PID=3102) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:38.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:38.796+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:38.796+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:38.822+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:38.820+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6
    from function import 
                         ^
SyntaxError: invalid syntax
[2024-11-13T23:20:38.823+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:38.851+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.067 seconds
[2024-11-13T23:20:44.030+0000] {processor.py:186} INFO - Started process (PID=3103) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:44.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:44.035+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:44.035+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:44.089+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:44.083+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function import c
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:20:44.092+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:44.126+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.106 seconds
[2024-11-13T23:20:45.338+0000] {processor.py:186} INFO - Started process (PID=3106) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:45.339+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:45.343+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:45.343+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:45.389+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:45.384+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function import co
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:20:45.391+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:45.419+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.088 seconds
[2024-11-13T23:20:47.470+0000] {processor.py:186} INFO - Started process (PID=3107) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:47.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:47.475+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:47.475+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:47.507+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:47.505+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6
    from function import 
                         ^
SyntaxError: invalid syntax
[2024-11-13T23:20:47.509+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:47.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.081 seconds
[2024-11-13T23:20:59.861+0000] {processor.py:186} INFO - Started process (PID=3114) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:59.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:20:59.871+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:59.870+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:59.904+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:20:59.902+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6
    from function.c import 
                           ^
SyntaxError: invalid syntax
[2024-11-13T23:20:59.906+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:20:59.938+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.088 seconds
[2024-11-13T23:21:01.025+0000] {processor.py:186} INFO - Started process (PID=3115) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:01.027+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:01.030+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:01.029+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:01.053+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:01.052+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6
    from function.cap import 
                             ^
SyntaxError: invalid syntax
[2024-11-13T23:21:01.054+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:01.082+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.066 seconds
[2024-11-13T23:21:16.576+0000] {processor.py:186} INFO - Started process (PID=3118) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:16.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:16.581+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:16.580+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:16.640+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:16.633+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import r
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:21:16.646+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:16.671+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.102 seconds
[2024-11-13T23:21:17.763+0000] {processor.py:186} INFO - Started process (PID=3119) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:17.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:17.769+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:17.768+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:17.821+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:17.813+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import read_s3_parquet
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:21:17.824+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:17.911+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.164 seconds
[2024-11-13T23:21:19.114+0000] {processor.py:186} INFO - Started process (PID=3120) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:19.133+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:19.138+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:19.137+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:19.183+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:19.181+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6
    from function.cap import read_s3_parquet,
                                             ^
SyntaxError: trailing comma not allowed without surrounding parentheses
[2024-11-13T23:21:19.184+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:19.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.118 seconds
[2024-11-13T23:21:20.178+0000] {processor.py:186} INFO - Started process (PID=3121) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:20.179+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:20.183+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:20.183+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:20.284+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:20.279+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import read_s3_parquet,t
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:21:20.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:20.323+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.159 seconds
[2024-11-13T23:21:22.352+0000] {processor.py:186} INFO - Started process (PID=3128) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:22.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:22.356+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:22.355+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:22.400+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:22.395+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import read_s3_parquet,table_tansformation
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:21:22.403+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:22.430+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.085 seconds
[2024-11-13T23:21:25.481+0000] {processor.py:186} INFO - Started process (PID=3129) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:25.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:25.486+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:25.485+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:25.539+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:25.533+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import read_s3_parquet,table_tansformation, tables_joining
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:21:25.542+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:25.569+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.095 seconds
[2024-11-13T23:21:26.603+0000] {processor.py:186} INFO - Started process (PID=3130) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:26.604+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:26.608+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:26.608+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:26.630+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:26.628+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6
    from function.cap import read_s3_parquet,table_tansformation, tables_joining,
                                                                                 ^
SyntaxError: trailing comma not allowed without surrounding parentheses
[2024-11-13T23:21:26.631+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:26.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.074 seconds
[2024-11-13T23:21:27.768+0000] {processor.py:186} INFO - Started process (PID=3131) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:27.769+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:27.773+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:27.773+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:27.819+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:27.814+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import read_s3_parquet,table_tansformation, tables_joining, c
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:21:27.821+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:27.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.098 seconds
[2024-11-13T23:21:28.807+0000] {processor.py:186} INFO - Started process (PID=3132) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:28.808+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:28.811+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:28.811+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:28.859+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:28.853+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:21:28.861+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:28.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.089 seconds
[2024-11-13T23:21:30.956+0000] {processor.py:186} INFO - Started process (PID=3133) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:30.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:30.960+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:30.960+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:30.981+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:30.979+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6
    from function.cap import read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
                                                                                                               ^
SyntaxError: trailing comma not allowed without surrounding parentheses
[2024-11-13T23:21:30.982+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:31.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.064 seconds
[2024-11-13T23:21:33.103+0000] {processor.py:186} INFO - Started process (PID=3134) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:33.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:33.107+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:33.107+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:33.132+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:33.130+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6
    from function.cap import read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
                                                                                                               ^
SyntaxError: trailing comma not allowed without surrounding parentheses
[2024-11-13T23:21:33.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:33.166+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.071 seconds
[2024-11-13T23:21:37.401+0000] {processor.py:186} INFO - Started process (PID=3135) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:37.403+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:37.406+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:37.406+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:37.446+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:37.441+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:21:37.448+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:37.473+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.080 seconds
[2024-11-13T23:21:40.489+0000] {processor.py:186} INFO - Started process (PID=3136) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:40.490+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:40.496+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:40.494+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:40.524+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:40.522+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet
                             ^
SyntaxError: '(' was never closed
[2024-11-13T23:21:40.525+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:40.566+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.090 seconds
[2024-11-13T23:21:44.635+0000] {processor.py:186} INFO - Started process (PID=3137) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:44.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:44.642+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:44.641+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:44.715+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:44.700+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet)
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:21:44.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:44.756+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.135 seconds
[2024-11-13T23:21:49.119+0000] {processor.py:186} INFO - Started process (PID=3140) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:49.120+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:49.124+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:49.123+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:49.166+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:49.160+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,)
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:21:49.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:49.199+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.087 seconds
[2024-11-13T23:21:51.240+0000] {processor.py:186} INFO - Started process (PID=3146) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:51.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:51.245+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:51.244+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:51.286+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:51.280+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:21:51.288+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:51.316+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.084 seconds
[2024-11-13T23:21:54.347+0000] {processor.py:186} INFO - Started process (PID=3147) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:54.349+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:54.353+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:54.353+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:54.539+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:54.534+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:21:54.541+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:54.571+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.231 seconds
[2024-11-13T23:21:58.631+0000] {processor.py:186} INFO - Started process (PID=3148) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:58.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:21:58.635+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:58.635+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:58.691+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:21:58.684+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:21:58.696+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:21:58.723+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.101 seconds
[2024-11-13T23:22:03.900+0000] {processor.py:186} INFO - Started process (PID=3149) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:03.902+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:22:03.904+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:03.904+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:03.954+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:03.948+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:22:03.957+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:03.992+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.099 seconds
[2024-11-13T23:22:05.969+0000] {processor.py:186} INFO - Started process (PID=3150) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:05.971+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:22:05.974+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:05.973+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:06.035+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:06.027+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:22:06.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:06.068+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.109 seconds
[2024-11-13T23:22:08.139+0000] {processor.py:186} INFO - Started process (PID=3151) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:08.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:22:08.143+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:08.143+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:08.183+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:08.178+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:22:08.185+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:08.216+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.083 seconds
[2024-11-13T23:22:16.489+0000] {processor.py:186} INFO - Started process (PID=3154) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:16.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:22:16.494+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:16.494+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:16.544+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:16.538+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:22:16.547+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:16.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.095 seconds
[2024-11-13T23:22:21.714+0000] {processor.py:186} INFO - Started process (PID=3161) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:21.715+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:22:21.718+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:21.717+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:21.761+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:21.755+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:22:21.763+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:21.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.082 seconds
[2024-11-13T23:22:22.795+0000] {processor.py:186} INFO - Started process (PID=3162) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:22.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:22:22.799+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:22.799+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:22.845+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:22.839+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:22:22.847+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:22.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.085 seconds
[2024-11-13T23:22:26.016+0000] {processor.py:186} INFO - Started process (PID=3163) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:26.017+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:22:26.022+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:26.021+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:26.066+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:26.059+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:22:26.069+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:26.097+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.088 seconds
[2024-11-13T23:22:30.161+0000] {processor.py:186} INFO - Started process (PID=3164) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:30.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:22:30.165+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:30.164+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:30.204+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:30.199+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:22:30.207+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:30.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.083 seconds
[2024-11-13T23:22:32.333+0000] {processor.py:186} INFO - Started process (PID=3165) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:32.334+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:22:32.337+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:32.336+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:32.381+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:32.375+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:22:32.383+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:32.414+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.088 seconds
[2024-11-13T23:22:34.419+0000] {processor.py:186} INFO - Started process (PID=3166) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:34.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:22:34.424+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:34.423+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:34.472+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:34.464+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:22:34.475+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:34.503+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.090 seconds
[2024-11-13T23:22:36.533+0000] {processor.py:186} INFO - Started process (PID=3167) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:36.534+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:22:36.541+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:36.538+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:36.593+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:22:36.587+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:22:36.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:22:36.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.101 seconds
[2024-11-13T23:23:04.387+0000] {processor.py:186} INFO - Started process (PID=3175) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:23:04.388+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:23:04.392+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:23:04.391+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:23:04.436+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:23:04.430+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:23:04.438+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:23:04.462+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.084 seconds
[2024-11-13T23:23:35.055+0000] {processor.py:186} INFO - Started process (PID=3184) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:23:35.057+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:23:35.060+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:23:35.059+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:23:35.088+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:23:35.083+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:23:35.091+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:23:35.114+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.066 seconds
[2024-11-13T23:23:39.146+0000] {processor.py:186} INFO - Started process (PID=3185) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:23:39.147+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:23:39.151+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:23:39.151+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:23:39.204+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:23:39.197+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:23:39.206+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:23:39.233+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.096 seconds
[2024-11-13T23:23:42.325+0000] {processor.py:186} INFO - Started process (PID=3186) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:23:42.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:23:42.329+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:23:42.329+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:23:42.371+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:23:42.366+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:23:42.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:23:42.403+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.085 seconds
[2024-11-13T23:24:08.493+0000] {processor.py:186} INFO - Started process (PID=3195) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:08.494+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:24:08.497+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:24:08.496+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:08.538+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:24:08.530+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:24:08.543+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:08.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.097 seconds
[2024-11-13T23:24:09.569+0000] {processor.py:186} INFO - Started process (PID=3196) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:09.580+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:24:09.585+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:24:09.585+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:09.648+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:24:09.642+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:24:09.652+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:09.692+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.145 seconds
[2024-11-13T23:24:10.802+0000] {processor.py:186} INFO - Started process (PID=3197) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:10.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:24:10.806+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:24:10.806+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:10.853+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:24:10.846+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:24:10.855+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:10.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.097 seconds
[2024-11-13T23:24:12.863+0000] {processor.py:186} INFO - Started process (PID=3198) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:12.864+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:24:12.867+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:24:12.867+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:12.916+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:24:12.909+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:24:12.919+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:12.951+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.095 seconds
[2024-11-13T23:24:43.952+0000] {processor.py:186} INFO - Started process (PID=3207) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:43.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:24:43.957+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:24:43.956+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:43.987+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:24:43.981+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet,table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:24:43.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:44.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.077 seconds
[2024-11-13T23:24:46.013+0000] {processor.py:186} INFO - Started process (PID=3208) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:46.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:24:46.018+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:24:46.018+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:46.081+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:24:46.073+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:24:46.084+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:24:46.109+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.105 seconds
[2024-11-13T23:25:16.597+0000] {processor.py:186} INFO - Started process (PID=3217) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:25:16.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:25:16.602+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:25:16.602+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:25:16.637+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:25:16.631+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:25:16.639+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:25:16.666+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.079 seconds
[2024-11-13T23:25:47.207+0000] {processor.py:186} INFO - Started process (PID=3225) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:25:47.209+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:25:47.212+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:25:47.211+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:25:47.244+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:25:47.238+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 6, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:25:47.247+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:25:47.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.087 seconds
[2024-11-13T23:26:06.965+0000] {processor.py:186} INFO - Started process (PID=3235) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:26:06.966+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:26:06.969+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:26:06.968+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:26:07.019+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:26:07.013+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 7, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:26:07.021+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:26:07.048+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.091 seconds
[2024-11-13T23:26:38.107+0000] {processor.py:186} INFO - Started process (PID=3245) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:26:38.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:26:38.113+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:26:38.112+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:26:38.147+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:26:38.142+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 7, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:26:38.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:26:38.183+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.086 seconds
[2024-11-13T23:27:08.909+0000] {processor.py:186} INFO - Started process (PID=3254) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:27:08.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:27:08.915+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:27:08.915+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:27:08.949+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:27:08.943+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 7, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:27:08.951+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:27:08.980+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.081 seconds
[2024-11-13T23:27:39.936+0000] {processor.py:186} INFO - Started process (PID=3263) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:27:39.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:27:39.940+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:27:39.940+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:27:39.980+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:27:39.973+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 7, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:27:39.982+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:27:40.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.090 seconds
[2024-11-13T23:28:10.542+0000] {processor.py:186} INFO - Started process (PID=3272) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:28:10.544+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:28:10.547+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:28:10.546+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:28:10.581+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:28:10.574+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 7, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:28:10.584+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:28:10.613+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.081 seconds
[2024-11-13T23:28:41.454+0000] {processor.py:186} INFO - Started process (PID=3282) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:28:41.455+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:28:41.459+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:28:41.458+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:28:41.492+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:28:41.487+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 7, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:28:41.494+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:28:41.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.078 seconds
[2024-11-13T23:29:12.196+0000] {processor.py:186} INFO - Started process (PID=3291) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:29:12.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:29:12.200+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:29:12.200+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:29:12.232+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:29:12.225+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 7, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:29:12.234+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:29:12.273+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.086 seconds
[2024-11-13T23:29:42.870+0000] {processor.py:186} INFO - Started process (PID=3300) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:29:42.872+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:29:42.877+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:29:42.876+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:29:42.909+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:29:42.903+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 7, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:29:42.912+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:29:42.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.076 seconds
[2024-11-13T23:30:13.494+0000] {processor.py:186} INFO - Started process (PID=3309) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:30:13.495+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:30:13.499+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:30:13.498+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:30:13.535+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:30:13.529+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 7, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:30:13.537+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:30:13.567+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.081 seconds
[2024-11-13T23:30:44.329+0000] {processor.py:186} INFO - Started process (PID=3319) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:30:44.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:30:44.336+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:30:44.335+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:30:44.366+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:30:44.361+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 7, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:30:44.368+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:30:44.393+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.074 seconds
[2024-11-13T23:31:14.997+0000] {processor.py:186} INFO - Started process (PID=3328) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:31:14.998+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:31:15.001+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:31:15.001+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:31:15.040+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:31:15.032+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 7, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:31:15.042+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:31:15.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.088 seconds
[2024-11-13T23:31:45.315+0000] {processor.py:186} INFO - Started process (PID=3337) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:31:45.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:31:45.319+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:31:45.318+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:31:45.356+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:31:45.349+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 7, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:31:45.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:31:45.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.087 seconds
[2024-11-13T23:32:16.411+0000] {processor.py:186} INFO - Started process (PID=3346) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:32:16.413+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:32:16.417+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:32:16.417+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:32:16.455+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:32:16.450+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 7, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:32:16.457+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:32:16.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.076 seconds
[2024-11-13T23:32:47.330+0000] {processor.py:186} INFO - Started process (PID=3355) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:32:47.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:32:47.334+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:32:47.334+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:32:47.361+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:32:47.356+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 7, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:32:47.363+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:32:47.386+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.064 seconds
[2024-11-13T23:33:17.877+0000] {processor.py:186} INFO - Started process (PID=3364) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:33:17.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:33:17.882+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:33:17.881+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:33:17.908+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:33:17.903+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 7, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:33:17.910+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:33:17.936+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.067 seconds
[2024-11-13T23:33:48.543+0000] {processor.py:186} INFO - Started process (PID=3373) to work on /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:33:48.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/capstone_airflow/country.py for tasks to queue
[2024-11-13T23:33:48.550+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:33:48.550+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:33:48.582+0000] {logging_mixin.py:190} INFO - [2024-11-13T23:33:48.576+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/capstone_airflow/country.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/capstone_airflow/country.py", line 7, in <module>
    from function.cap import (read_s3_parquet, table_tansformation, tables_joining, country_transform_s3_parquet,
ModuleNotFoundError: No module named 'function'
[2024-11-13T23:33:48.584+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/capstone_airflow/country.py
[2024-11-13T23:33:48.620+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/capstone_airflow/country.py took 0.087 seconds
